config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/movie_genres/showall', to: 'movie_genres#showall', as: "showall_movie_genres"
  resources :movie_genres, only: [:show, :new, :create, :edit, :update, :destroy]
  get '/directors/showall', to: 'directors#showall', as: 'showall_directors'
  resources :directors, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'movies/show-drafts', to: 'movies#show_drafts', as: 'show_draft_movies'
  resources :movies, only: [:show, :new, :create, :edit, :update, :destroy] do
    patch :publish, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :movie_genre
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :movie_genre
  has_one_attached :cover
  enum status: {draft: 0, published: 1}
  enum movie_status: {soon: 0, released: 1}
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  has_many :directors
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

  def showall
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
    @movies = Movie.where(director_id: @director.id)
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(name: params[:director][:name],
                              nacionality: params[:director][:nacionality],
                              birth_date: params[:director][:birth_date],
                              movie_genre_id: params[:director][:movie_genre_id]
                              )
    if @director.save
      flash[:notice] = "Informações foram salvas com sucesso! ✅"
      return redirect_to new_director_path
    end
    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])
    if @director.update(name: params[:director][:name],
                        nacionality: params[:director][:nacionality],
                        birth_date: params[:director][:birth_date],
                        movie_genre_id: params[:director][:movie_genre_id]
                        )
      flash[:notice] = 'Informações atualizadas com sucesso!'
      return redirect_to director_path(@director.id)
    end
    render :edit
  end

  def destroy
    @director = Director.find(params[:id])
    @director.destroy
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.published
  end
end

app/controllers/movie_genres_controller.rb
class MovieGenresController < ApplicationController

  def showall
    @movie_genres = MovieGenre.all
  end

  def show
    @movie_genre = MovieGenre.find(params[:id])
    @movies = Movie.where(movie_genre_id: @movie_genre.id)
  end

  def new
    @movie_genre = MovieGenre.new
  end

  def create
    @movie_genre = MovieGenre.new(genre: params[:movie_genre][:genre])
    if @movie_genre.save
      flash[:notice] = "Informações foram salvas com sucesso! ✅"
      return redirect_to new_movie_genre_path
    end
    render :new
  end

  def edit
    @movie_genre = MovieGenre.find(params[:id])
  end

  def update
    @movie_genre = MovieGenre.find(params[:id])
    if @movie_genre.update(genre: params[:movie_genre][:genre])
      flash[:notice] = 'Informações atualizadas com sucesso!'
      return redirect_to movie_genre_path(@movie_genre.id)
    end
    render :edit
  end

  def destroy
    @movie_genre = MovieGenre.find(params[:id])
    @movie_genre.destroy
    redirect_to root_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def show
    @movie = Movie.find(params[:id])
  end

  def show_drafts
    @movies = Movie.draft
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(get_params)
    if params[:movie][:movie_status] == "1"
      @movie.released!
    else
      @movie.soon!
    end

    if params[:movie][:status] == "1"
      @movie.published!
    else
      @movie.draft!
    end

    if @movie.save
      flash[:notice] = "Informações foram salvas com sucesso! ✅"
      return redirect_to new_movie_path
    end
    render :new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(get_params)
      if params[:movie][:movie_status] == "1"
        @movie.released!
      else
        @movie.soon!
      end

      if params[:movie][:status] == "1"
        @movie.published!
      else
        @movie.draft!
      end

      flash[:notice] = 'Informações atualizadas com sucesso!'
      return redirect_to movie_path(@movie.id)
    end
    render :edit
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to root_path
  end

  def publish
    movie = Movie.find(params[:id])
    if movie.published?
      movie.draft!
    else
      movie.published!
    end
    return redirect_to movie_path(movie.id)
  end

  private

  def get_params
    params.require(:movie).permit(:title, :release_date, :sinopsis, :country, :duration, :movie_genre_id, :director_id, :cover)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<%= form_for @director do |f| %>
  <%= f.label :name, 'Nome:' %>
  <%= f.text_field :name %>
  <%= f.label :nacionality, 'Nacionalidade:' %>
  <%= f.text_field :nacionality %>
  <%= f.label :birth_date, 'Data de nascimento:' %>
  <%= f.text_field :birth_date %>
  <%= f.label :movie_genre, 'Gênero favorito:' %>
  <%= f.collection_select :movie_genre_id, MovieGenre.all, :id, :genre %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/directors/edit.html.erb
<h1>Editar um diretor</h1>

<%= render partial: 'form', locals: {director: @director}%>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/directors/new.html.erb
<h1>Criar um novo diretor</h1>

<%= form_for @director do |f| %>
  <%= f.label :name, 'Nome:' %>
  <%= f.text_field :name %>
  <%= f.label :nacionality, 'Nacionalidade:' %>
  <%= f.text_field :nacionality %>
  <%= f.label :birth_date, 'Data de nascimento:' %>
  <%= f.text_field :birth_date %>
  <%= f.label :movie_genre, 'Gênero favorito:' %>
  <%= f.collection_select :movie_genre_id, MovieGenre.all, :id, :genre %>
  <%= f.submit 'Criar' %>
<% end %>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/directors/show.html.erb
<h1><strong>Informações sobre o diretor <%= @director.name %></strong></h1>

<dt>
  <dl>Nacionalidade: <%= @director.nacionality%></dl>
  <dl>Data de nascimento: <%= @director.birth_date%></dl>
  <dl>Gênero Favorito: <%= MovieGenre.find(@director.movie_genre_id).genre%></dl>
</dt>

<button><%= link_to 'Editar', edit_director_path%></button>

<h2>Filmes desse diretor</h2>

<%@movies.each do |movie|%>
  <p>
    <strong>Filme: </strong><%= movie.title%> (<%= movie.release_date%>)
  </p>
<%end%>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/directors/showall.html.erb
<h1>Listando os diretores</h1>

<div class="movie-container">
  <% @directors.each do |director| %>
    <div class="movie-card">
      <p>
        <strong>Diretor: </strong><%= director.name %>
        <div class="button-container">
          <button><%= link_to 'Ver mais', director %></button>
          <button><%= link_to 'Apagar', director, data: { turbo_method: :delete, turbo_confirm: 'Tem certeza que deseja apagar?' } %></button>
        </div>
      </p>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Listagem dos filmes</h1>

<div class="movie-container">
  <% @movies.each do |movie| %>
    <div class="movie-card">
      <% if movie.cover.attached? %>
        <%= image_tag movie.cover, height: 200 %>
      <% end %>
      <p>
        <strong>Filme: </strong><%= movie.title %> (<%= movie.release_date %>) [<%= movie.movie_status %>]
        <div class="button-container">
          <button><%= link_to 'Ver mais', movie %></button>
          <button><%= link_to 'Apagar', movie, data: { turbo_method: :delete, turbo_confirm: 'Tem certeza que deseja apagar?' } %></button>
        </div>
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilmCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "global", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav style="display: flex; justify-content: center; align-itens: center">
      <div>
        <button><%= link_to 'adicionar um novo gênero', new_movie_genre_path %></button>
        <button><%= link_to 'listar os gêneros', showall_movie_genres_path %></button>

        <button><%= link_to 'adicionar um novo diretor', new_director_path %></button>
        <button><%= link_to 'listar os diretores', showall_directors_path %></button>

        <button><%= link_to 'cadastrar um novo filme', new_movie_path %></button>
        <button><%= link_to 'mostrar os rascunhos', show_draft_movies_path %></button>

        <button><%= link_to 'back to home', root_path %></button>
      </div>
    </nav>


    <%= yield %>


    <footer>
      <button><%= link_to 'back to home', root_path %></button>
    </footer>
  </body>
</html>

app/views/movie_genres/edit.html.erb
<h1>Editar um gênero de filme</h1>

<%= form_for @movie_genre do |f| %>
  <%= f.label :genre, 'Gênero:' %>
  <%= f.text_field :genre %>
  <%= f.submit 'Editar' %>

<% end %>
<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/movie_genres/new.html.erb
<h1>Criar um novo gênero de filme</h1>

<%= form_for @movie_genre do |f| %>
  <%= f.label :genre, 'Gênero:' %>
  <%= f.text_field :genre %>
  <%= f.submit 'Criar' %>
<% end %>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/movie_genres/show.html.erb
<h1><strong>Gênero: <%= @movie_genre.genre %></strong></h1>

<button><%= link_to 'Editar', edit_movie_genre_path%></button>

<h2>Filmes do Gênero <%= @movie_genre.genre%></h2>

<%@movies.each do |movie|%>
  <p>
    <strong>Filme: </strong><%= movie.title%> (<%= movie.release_date%>)
  </p>
<%end%>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/movie_genres/showall.html.erb
<h1>Listando os gêneros</h1>

<div class="movie-container">
  <% @movie_genres.each do |movie_genre| %>
    <div class="movie-card">
      <p>
        <strong>Gênero: </strong><%= movie_genre.genre %>
        <div class="button-container">
          <button><%= link_to 'Ver mais', movie_genre %></button>
          <button><%= link_to 'Apagar', movie_genre, data: { turbo_method: :delete, turbo_confirm: 'Tem certeza que deseja apagar?' } %></button>
        </div>
      </p>
    </div>
  <% end %>
</div>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <%= f.label :title, 'Título:' %>
  <%= f.text_field :title %>
  <%= f.label :release_date, 'Ano de lançamento:' %>
  <%= f.text_field :release_date %>
  <%= f.label :sinopsis, 'Sinopse:' %>
  <%= f.text_area :sinopsis %>
  <%= f.label :country, 'País de origem:' %>
  <%= f.text_field :country %>
  <%= f.label :duration, 'Duração (minutos):' %>
  <%= f.number_field :duration %><br><br>
  <%= f.label :movie_genre, 'Gênero favorito:' %>
  <%= f.collection_select :movie_genre_id, MovieGenre.all, :id, :genre %>
  <%= f.label :director, 'Diretor:' %>
  <%= f.collection_select :director_id, Director.all, :id, :name %>
  <%= f.label :movie_status, 'Filme já lançado' %>
  <%= f.check_box :movie_status %><br><br>
  <%= f.label :status, 'Publicar' %>
  <%= f.check_box :status %><br><br>
  <%= f.label :cover %>
  <%= f.file_field :cover %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editar um filme</h1>

<%= render partial: 'form', locals: {movie: @movie}%>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/movies/new.html.erb
<h1>Cadastrar um novo filme</h1>

<%= render partial: 'form', locals: {movie: @movie}%>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/movies/show.html.erb
<h1><strong>Exibindo as informações de : <%= @movie.title %></strong></h1>

<dt>
  <dd><h2>Detalhes do filme</h2></dd>
  <dl>Ano de lançamento: <%= @movie.release_date%></dl>
  <dl>Sinopse: <%= @movie.sinopsis%></dl>
  <dl>País de origem: <%= @movie.country%></dl>
  <dl>Duração: <%= @movie.duration%> min.</dl>
  <dl>Gênero: <%= MovieGenre.find(@movie.movie_genre_id).genre%></dl>
  <dl>Diretor: <%= Director.find(@movie.director_id).name%></dl>
</dt>

<% if @movie.cover.attached? %>
  <%= image_tag @movie.cover, height: 200 %>
<% end %>

<button><%= link_to 'Editar', edit_movie_path%></button>
<% if not @movie.published?%>
  <%= button_to 'Publicar', publish_movie_path, {method: 'patch'}%>
<% else %>
  <%= button_to 'Tornar rascunho', publish_movie_path, {method: 'patch'}%>
<% end %>

<% if flash[:notice] %>
  <div class="flash-warning">
    <%= flash[:notice] %>
  </div>
<%end%>

app/views/movies/show_drafts.html.erb
<h1>Mostrando os rascunhos</h1>

<dl>
  <%@movies.each do |movie|%>
    <% if movie.cover.attached? %>
      <%= image_tag movie.cover, height: 200 %>
    <% end %>
    <p>
      <strong>Filme: </strong><%= movie.title%> (<%= movie.release_date%>) [<%= movie.movie_status%>]
      <div style="width: 10vw; display: flex;">
        <button><%= link_to 'Ver mais', movie%></button>
        <button><%= link_to 'Apagar', movie, data: {turbo_method: :delete, turbo_confirm: 'Tem certeza que deseja apagar?'}%></button>
        <%= button_to 'Publicar', publish_movie_path(movie.id), {method: 'patch'}%>
      </div>
    </p>
  <%end%>
</dl>